version: "3.9"
services:
  notebook:
    image: my-jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - notebooks:/home/jovyan/work
      - ./cardata.csv:/home/jovyan/work/cardata.csv
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=my_token

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  notebooks:
